// GENERATED by komodobots experiments/route_policy/gen_routepolicy_table.py -- DO NOT EDIT.
// source: milton_reference_dm3.json sha256/12=0f4660126569 (extracted 2026-07-07)
// corpus: 15 demos, 562 transitions, 347 spawns, player filter 'milton'
// method: pickups-only resource visits (/items takenBy); death resets chain; self-loops counted; spawn cluster = loc of nearest info_player_deathmatch entity
#ifndef KBOT_ROUTEPOLICY_DM3_H
#define KBOT_ROUTEPOLICY_DM3_H

// resource nodes (the dm3 route-policy vocabulary)
enum rp_node_dm3 {
	RP_DM3_PENT = 0,
	RP_DM3_PENT_MH = 1,
	RP_DM3_QUAD = 2,
	RP_DM3_RA = 3,
	RP_DM3_RL = 4,
	RP_DM3_RING = 5,
	RP_DM3_SNG = 6,
	RP_DM3_SNG_MH = 7,
	RP_DM3_YA_BOX = 8,
	RP_DM3_HILL = 9,
	RP_DM3_WATER_GL = 10,
	RP_DM3_WATER_LG = 11,
	RP_DM3_NUM_NODES = 12
};

// spawn-opening synthetic outcome columns (after the node columns)
#define RP_OPEN_COMBAT      12   // died within the opening window
#define RP_OPEN_NONE        13   // no resource reached in the window
#define RP_NUM_OPEN_COLS    14
#define RP_DM3_NUM_SPAWNS   5
#define RP_MIN_ROW_SUPPORT  10  // rows below this total are too sparse to trust
#define RP_OPENING_WINDOW_S 12.0f

static const char *rp_node_name_dm3[RP_DM3_NUM_NODES] = {
	"Pent", "Pent.MH", "Quad", "RA", "RL", "Ring", "SNG", "SNG.MH", "YA.box", "hill", "water.GL", "water.LG"
};

// pooled Milton resource-transition counts, row = from, col = to
static const int rp_trans_count_dm3[RP_DM3_NUM_NODES][RP_DM3_NUM_NODES] = {
	{0, 2, 3, 2, 0, 0, 0, 0, 2, 1, 1, 3},  // Pent
	{1, 0, 1, 6, 3, 0, 5, 0, 4, 2, 2, 1},  // Pent.MH
	{1, 4, 0, 16, 0, 0, 0, 3, 17, 3, 0, 1},  // Quad
	{6, 1, 20, 11, 4, 3, 20, 4, 13, 18, 1, 5},  // RA
	{0, 4, 1, 6, 0, 0, 0, 0, 23, 2, 2, 2},  // RL
	{0, 0, 4, 3, 0, 0, 0, 0, 0, 2, 0, 0},  // Ring
	{0, 0, 5, 12, 0, 1, 3, 44, 1, 1, 0, 0},  // SNG
	{0, 0, 2, 22, 2, 1, 4, 0, 11, 8, 0, 0},  // SNG.MH
	{3, 9, 9, 13, 8, 0, 23, 2, 24, 4, 1, 6},  // YA.box
	{1, 1, 8, 18, 4, 0, 3, 0, 6, 0, 6, 5},  // hill
	{1, 3, 0, 5, 4, 0, 0, 1, 5, 1, 0, 3},  // water.GL
	{1, 4, 0, 7, 1, 0, 1, 1, 6, 4, 4, 0},  // water.LG
};

// per-row totals: rp_row_total_dm3[i] < RP_MIN_ROW_SUPPORT => sparse row
static const int rp_row_total_dm3[RP_DM3_NUM_NODES] = {
	14, 25, 45, 106, 40, 9, 67, 50, 102, 52, 23, 29
};

// P(next resource | current resource); all-zero row when total = 0
static const float rp_trans_prob_dm3[RP_DM3_NUM_NODES][RP_DM3_NUM_NODES] = {
	{0.0000f, 0.1429f, 0.2143f, 0.1429f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.1429f, 0.0714f, 0.0714f, 0.2143f},  // Pent
	{0.0400f, 0.0000f, 0.0400f, 0.2400f, 0.1200f, 0.0000f, 0.2000f, 0.0000f, 0.1600f, 0.0800f, 0.0800f, 0.0400f},  // Pent.MH
	{0.0222f, 0.0889f, 0.0000f, 0.3556f, 0.0000f, 0.0000f, 0.0000f, 0.0667f, 0.3778f, 0.0667f, 0.0000f, 0.0222f},  // Quad
	{0.0566f, 0.0094f, 0.1887f, 0.1038f, 0.0377f, 0.0283f, 0.1887f, 0.0377f, 0.1226f, 0.1698f, 0.0094f, 0.0472f},  // RA
	{0.0000f, 0.1000f, 0.0250f, 0.1500f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.5750f, 0.0500f, 0.0500f, 0.0500f},  // RL
	{0.0000f, 0.0000f, 0.4444f, 0.3333f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.2222f, 0.0000f, 0.0000f},  // Ring
	{0.0000f, 0.0000f, 0.0746f, 0.1791f, 0.0000f, 0.0149f, 0.0448f, 0.6567f, 0.0149f, 0.0149f, 0.0000f, 0.0000f},  // SNG
	{0.0000f, 0.0000f, 0.0400f, 0.4400f, 0.0400f, 0.0200f, 0.0800f, 0.0000f, 0.2200f, 0.1600f, 0.0000f, 0.0000f},  // SNG.MH
	{0.0294f, 0.0882f, 0.0882f, 0.1275f, 0.0784f, 0.0000f, 0.2255f, 0.0196f, 0.2353f, 0.0392f, 0.0098f, 0.0588f},  // YA.box
	{0.0192f, 0.0192f, 0.1538f, 0.3462f, 0.0769f, 0.0000f, 0.0577f, 0.0000f, 0.1154f, 0.0000f, 0.1154f, 0.0962f},  // hill
	{0.0435f, 0.1304f, 0.0000f, 0.2174f, 0.1739f, 0.0000f, 0.0000f, 0.0435f, 0.2174f, 0.0435f, 0.0000f, 0.1304f},  // water.GL
	{0.0345f, 0.1379f, 0.0000f, 0.2414f, 0.0345f, 0.0000f, 0.0345f, 0.0345f, 0.2069f, 0.1379f, 0.1379f, 0.0000f},  // water.LG
};

// spawn clusters, ordered by observed spawn count
static const char *rp_spawn_name_dm3[RP_DM3_NUM_SPAWNS] = {
	"SNG.tele", "RL", "RA.tunnel", "YA.box", "lifts"
};

// spawn-opening counts: row = spawn cluster, col = node id or RP_OPEN_COMBAT/RP_OPEN_NONE
static const int rp_open_count_dm3[RP_DM3_NUM_SPAWNS][RP_NUM_OPEN_COLS] = {
	{0, 0, 2, 5, 0, 2, 2, 1, 2, 4, 0, 1, 71, 28},  // SNG.tele
	{0, 1, 0, 0, 10, 0, 0, 0, 0, 0, 6, 4, 27, 18},  // RL
	{0, 0, 0, 0, 1, 0, 0, 0, 0, 5, 5, 3, 29, 19},  // RA.tunnel
	{0, 1, 0, 0, 2, 0, 0, 0, 9, 0, 0, 1, 18, 21},  // YA.box
	{0, 1, 1, 1, 1, 0, 6, 0, 0, 5, 2, 0, 19, 13},  // lifts
};

static const int rp_open_total_dm3[RP_DM3_NUM_SPAWNS] = {
	118, 66, 62, 52, 49
};

// P(opening | spawn cluster)
static const float rp_open_prob_dm3[RP_DM3_NUM_SPAWNS][RP_NUM_OPEN_COLS] = {
	{0.0000f, 0.0000f, 0.0169f, 0.0424f, 0.0000f, 0.0169f, 0.0169f, 0.0085f, 0.0169f, 0.0339f, 0.0000f, 0.0085f, 0.6017f, 0.2373f},  // SNG.tele
	{0.0000f, 0.0152f, 0.0000f, 0.0000f, 0.1515f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0909f, 0.0606f, 0.4091f, 0.2727f},  // RL
	{0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0161f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0806f, 0.0806f, 0.0484f, 0.4677f, 0.3065f},  // RA.tunnel
	{0.0000f, 0.0192f, 0.0000f, 0.0000f, 0.0385f, 0.0000f, 0.0000f, 0.0000f, 0.1731f, 0.0000f, 0.0000f, 0.0192f, 0.3462f, 0.4038f},  // YA.box
	{0.0000f, 0.0204f, 0.0204f, 0.0204f, 0.0204f, 0.0000f, 0.1224f, 0.0000f, 0.0000f, 0.1020f, 0.0408f, 0.0000f, 0.3878f, 0.2653f},  // lifts
};

// node keying origins (map facts, lab/dashboard map_entities): the C side
// binds each node id to the nearest live item edict at map init
static const float rp_node_org_dm3[RP_DM3_NUM_NODES][3] = {
	{1008.0f, 800.0f, -296.0f},  // Pent
	{1840.0f, 624.0f, -204.0f},  // Pent.MH
	{952.0f, 296.0f, 56.0f},  // Quad
	{256.0f, -704.0f, 304.0f},  // RA
	{1520.0f, 496.0f, -112.0f},  // RL
	{240.0f, -32.0f, 56.0f},  // Ring
	{-512.0f, 448.0f, 96.0f},  // SNG
	{-720.0f, 80.0f, 160.0f},  // SNG.MH
	{1232.0f, -904.0f, -48.0f},  // YA.box
	{564.0f, -48.0f, -192.0f},  // hill
	{1216.0f, 240.0f, -416.0f},  // water.GL
	{1544.0f, -192.0f, -416.0f},  // water.LG
};

// info_player_deathmatch points -> cluster index (nearest-point classify)
#define RP_DM3_NUM_SPAWNPTS 6
static const float rp_spawnpt_org_dm3[RP_DM3_NUM_SPAWNPTS][3] = {
	{192.0f, -208.0f, -176.0f},  // RA.tunnel
	{1520.0f, 432.0f, -88.0f},  // RL
	{-880.0f, -232.0f, -16.0f},  // SNG.tele
	{-632.0f, -680.0f, -16.0f},  // SNG.tele
	{1472.0f, -928.0f, -24.0f},  // YA.box
	{512.0f, 768.0f, 216.0f},  // lifts
};
static const int rp_spawnpt_cluster_dm3[RP_DM3_NUM_SPAWNPTS] = {
	2, 1, 0, 0, 3, 4  // RA.tunnel, RL, SNG.tele, SNG.tele, YA.box, lifts
};

#endif // KBOT_ROUTEPOLICY_DM3_H
