// GENERATED by komodobots experiments/combat_rates/gen_combatrates_table.py -- DO NOT EDIT.
// source: milton_combat_rates_dm3.json sha256/12=d63085fa1a0b (extracted 2026-07-07)
// corpus: 15 demos, 2506 contacts, 770 cold hits, 1118 kills, player '[tVS]Milton'
#ifndef KBOT_COMBATRATES_DM3_H
#define KBOT_COMBATRATES_DM3_H

// Milton presses ~2/3 of combat contacts, flat across stack; the
// empirical disengage rate replaces CHANCE_EVADE_DUEL/NONDUEL (.08/.10).
#define CR_EVADE_CHANCE      0.3579f  // 1 - P(press), n=2506
// P(turn toward a cold-hit attacker); replaces the omniscient
// firepower comparator in BotDamageInflictedEvent for kbots.
#define CR_PAINSWITCH_CHANCE 0.6390f  // n=770

// P(kill weapon | range band) -- provenance only, NOT wired
// (availability-confounded; do not use for weapon choice as-is).
#define CR_NUM_BANDS   4
#define CR_NUM_WEAPONS 6
#ifdef KBOT_CR_WEAPON_TABLE
static const char *cr_band_label[CR_NUM_BANDS] = {
	"0-200", "200-500", "500-1000", "1000+"
};
static const char *cr_weapon_name[CR_NUM_WEAPONS] = {
	"rl", "lg", "sg", "sng", "ssg", "gl"
};
static const float cr_weapon_prob[CR_NUM_BANDS][CR_NUM_WEAPONS] = {
	{0.3902f, 0.1293f, 0.1659f, 0.2098f, 0.0610f, 0.0439f},  // 0-200 n=410
	{0.6021f, 0.1761f, 0.1461f, 0.0282f, 0.0176f, 0.0299f},  // 200-500 n=568
	{0.6493f, 0.1269f, 0.1940f, 0.0000f, 0.0075f, 0.0224f},  // 500-1000 n=134
	{0.8333f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.1667f},  // 1000+ n=6
};
#endif // KBOT_CR_WEAPON_TABLE

#endif // KBOT_COMBATRATES_DM3_H
