/*
 kbot_threataim.c -- clear-state crosshair placement (komodobots2 issue #29).

 When a humanmode komodobot has no enemy to aim at, its crosshair rests where
 an enemy is most likely to next appear: the Milton-derived static threat
 table (P(first-contact origin | own cell), 10 tVS DM3 4on4 MVDs, 2,858
 contacts) weighted by humanmode beliefs, at enemy-body height, on a
 150-350 ms hold/snap cadence, decoupled from movement.

 Spec: komodobots2 docs/specs/2026-07-06-kbot-threataim-implementation.md.
 Data: src/kbot_threataim_dm3.h, GENERATED by tools/gen_threataim_table.py.

 Humanmode-clean contract: the scorer reads ONLY the generated static table,
 HMode_* belief accessors, own fb perception state and own position. The one
 exception is [ta-contact] telemetry (k_hm_debug), which measures the
 first-sight angular error against the real enemy -- measurement, not
 decision input.

 Master cvar k_kbot_threataim (0 = off, bit-identical vanilla):
   1  static table + hold/snap cadence          (M-B)
   2  + hm belief weighting B_sight/B_item/B_tm (M-C)
   3  + staleness alternation + rear checks     (M-D)
 */

#ifdef BOT_SUPPORT

#include "g_local.h"
#include "hm.h"
#include "kbot.h"
#include "kbot_threataim_dm3.h"

#define TA_EYE_Z          22.0f
#define TA_KEY_MAX_DIST   700.0f	// nearest loc point further away: keep cell
#define TA_MIN_AIM_DIST   80.0f		// closer anchors are degenerate
#define TA_BAND_MIN       250.0f	// study range band (T7)
#define TA_BAND_MAX       600.0f
#define TA_STALE_HORIZON  10.0f		// staleness saturates after this many s
#define TA_ITEM_SOON      15.0f		// item up/<=15s out boosts its approach
#define TA_TM_COVER_DIST  256.0f
#define TA_APPROACH_HOPS  2			// sighting influence radius, adjacency steps

typedef struct ta_bot_s
{
	int cell;						// current cell id (-1 = unknown)
	int held;						// global ta_threat index (-1 = none)
	float hold_until;				// reselect deadline
	float next_key;					// cell-keying scan throttle
	float next_rear;				// next rear-check hold due
	qbool was_clear;				// [ta-contact] rising-edge latch
	float last_held[TA_NUM_THREATS];	// staleness clocks
} ta_bot_t;

static ta_bot_t ta_bots[MAX_CLIENTS + 1];
static gedict_t *ta_cell_item[TA_NUM_CELLS];	// tracked major in the cell
static qbool ta_map_ok;

// cvar cache, one throttled refresh for all bots (cvar() is a trap)
static float ta_cvar_next;
static int   ta_tier;
static float ta_hold_min, ta_hold_max, ta_pitch_cap, ta_rear_period;
static float ta_w_sight, ta_w_item;
static qbool ta_debug;

static void TA_RefreshCvars(void)
{
	float v;

	if (g_globalvars.time < ta_cvar_next)
	{
		return;
	}
	ta_cvar_next = g_globalvars.time + 0.5f;

	ta_tier = (int)cvar("k_kbot_threataim");
	v = cvar("k_kbot_ta_hold_min");
	ta_hold_min = (v > 0) ? v / 1000.0f : 0.15f;
	v = cvar("k_kbot_ta_hold_max");
	ta_hold_max = (v > 0) ? v / 1000.0f : 0.35f;
	if (ta_hold_max < ta_hold_min)
	{
		ta_hold_max = ta_hold_min;
	}
	v = cvar("k_kbot_ta_pitch_cap");
	ta_pitch_cap = (v > 0) ? v : 25.0f;
	v = cvar("k_kbot_ta_rear_period");
	ta_rear_period = (v > 0) ? v : 5.0f;
	v = cvar("k_kbot_ta_w_sight");
	ta_w_sight = (v > 0) ? v : 1.0f;
	v = cvar("k_kbot_ta_w_item");
	ta_w_item = (v > 0) ? v : 0.5f;
	ta_debug = cvar("k_hm_debug") != 0;
}

// Nearest-loc-point cell keying: the same attribution rule the study used.
// Returns -1 when nothing is within TA_KEY_MAX_DIST.
static int TA_CellForOrg(const float *org)
{
	int i, best = -1;
	float best_d = TA_KEY_MAX_DIST * TA_KEY_MAX_DIST;

	for (i = 0; i < TA_NUM_LOCPTS; i++)
	{
		float dx = org[0] - ta_locpt_dm3[i].org[0];
		float dy = org[1] - ta_locpt_dm3[i].org[1];
		float dz = org[2] - ta_locpt_dm3[i].org[2];
		float d = dx * dx + dy * dy + dz * dz;

		if (d < best_d)
		{
			best_d = d;
			best = ta_locpt_dm3[i].cell;
		}
	}

	return best;
}

void KBot_ThreatAimMapInit(void)
{
	gedict_t *p;
	int i;

	memset(ta_bots, 0, sizeof(ta_bots));
	for (i = 0; i <= MAX_CLIENTS; i++)
	{
		ta_bots[i].cell = -1;
		ta_bots[i].held = -1;
	}
	memset(ta_cell_item, 0, sizeof(ta_cell_item));
	ta_cvar_next = 0;

	ta_map_ok = streq(mapname, "dm3");
	if (!ta_map_ok)
	{
		return;
	}

	// Key each cell to a tracked major item spawned inside it (fixed map
	// facts: entity classnames + origins). The belief question about the
	// item goes through HMode_ItemRespawnTime at score time.
	for (p = world; (p = nextent(p));)
	{
		const char *cn = p->classname;
		int cell;

		if (!cn || !cn[0])
		{
			continue;
		}
		if (!streq(cn, "item_armor1") && !streq(cn, "item_armor2")
				&& !streq(cn, "item_armorInv") && !streq(cn, "item_health")
				&& !streq(cn, "weapon_rocketlauncher") && !streq(cn, "weapon_lightning")
				&& !streq(cn, "weapon_grenadelauncher") && !streq(cn, "weapon_supernailgun")
				&& !streq(cn, "item_artifact_super_damage")
				&& !streq(cn, "item_artifact_invulnerability"))
		{
			continue;
		}
		if (streq(cn, "item_health") && !((int)p->s.v.spawnflags & 2))
		{
			continue; // only megas are timed majors
		}

		cell = TA_CellForOrg(p->s.v.origin);
		if ((cell >= 0) && !ta_cell_item[cell])
		{
			ta_cell_item[cell] = p;
		}
	}

	if (cvar("k_hm_debug"))
	{
		G_cprint("[ta-init] map=%s cells=%d locpts=%d threats=%d\n",
					mapname, TA_NUM_CELLS, TA_NUM_LOCPTS, TA_NUM_THREATS);
	}
}

static qbool TA_Clear(gedict_t *self)
{
	if (ISDEAD(self) || intermission_running)
	{
		return false;
	}
	if (self->fb.enemy_visible)
	{
		return false;
	}
	if (self->fb.look_object && (self->fb.look_object->ct == ctPlayer))
	{
		return false;
	}
	if (self->fb.rocketJumping || self->fb.waterjumping)
	{
		return false;
	}
	if (KBot_GapjumpBusy(self))
	{
		return false;
	}

	return true;
}

// B_sight: believed enemies (S7 ring via the sanctioned accessor) boost
// threat points whose provenance cell is within TA_APPROACH_HOPS adjacency
// steps of the sighting's cell. Powerup carriers double the term.
static float TA_BSight(gedict_t *self, const ta_threat_t *t)
{
	const hm_sight_t *ring;
	int i, n = HMode_Sightings(self, &ring);
	float b = 1.0f;

	for (i = 0; i < n; i++)
	{
		const hm_sight_t *s = &ring[i];
		float age;
		int cell;

		if ((s->time <= 0) || !s->org_known)
		{
			continue;
		}
		age = g_globalvars.time - s->time;
		if ((age < 0) || (age > HMODE_SIGHT_TTL))
		{
			continue;
		}
		cell = TA_CellForOrg(s->org);
		if ((cell < 0) || (ta_hops_dm3[cell][t->from_cell] > TA_APPROACH_HOPS))
		{
			continue;
		}
		b *= 1.0f + ta_w_sight * (1.0f - age / HMODE_SIGHT_TTL)
				* (s->powerup ? 2.0f : 1.0f);
	}

	return b;
}

// B_item: an opening toward a major that is up (or <= 15 s out, per the
// bot's BELIEF) is hotter -- enemies path toward spawning items.
static float TA_BItem(gedict_t *self, const ta_threat_t *t)
{
	gedict_t *item = ta_cell_item[t->from_cell];
	float r;

	if (!item)
	{
		return 1.0f;
	}
	r = HMode_ItemRespawnTime(self, item);
	if (r <= g_globalvars.time + TA_ITEM_SOON)
	{
		return 1.0f + ta_w_item;
	}

	return 1.0f;
}

// B_tm: a fresh-believed teammate standing on the opening halves its threat.
static float TA_BTm(gedict_t *self, const ta_threat_t *t)
{
	int i;
	float b = 1.0f;

	for (i = 1; i <= MAX_CLIENTS; i++)
	{
		gedict_t *mate = &g_edicts[i];
		const hm_tm_t *info;
		float dx, dy, dz;

		if ((mate == self) || (mate->ct != ctPlayer) || !SameTeam(mate, self))
		{
			continue;
		}
		info = HMode_TeammateInfo(self, mate);
		if (!info || !info->fresh || !info->loc_known)
		{
			continue;
		}
		dx = info->org[0] - t->org[0];
		dy = info->org[1] - t->org[1];
		dz = info->org[2] - t->org[2];
		if ((dx * dx + dy * dy + dz * dz)
				< (TA_TM_COVER_DIST * TA_TM_COVER_DIST))
		{
			b *= 0.5f;
		}
	}

	return b;
}

static void TA_Eye(gedict_t *self, vec3_t eye)
{
	VectorCopy(self->s.v.origin, eye);
	eye[2] += TA_EYE_Z;
}

// The BotSetDesiredAngles pitch-sign fix (bot_aim.c): positive = down.
static void TA_AnglesTo(gedict_t *self, const float *org, vec3_t out)
{
	vec3_t eye, rel;

	TA_Eye(self, eye);
	VectorSubtract(org, eye, rel);
	vectoangles(rel, out);
	if (out[0] > 180)
	{
		out[0] = 360 - out[0];
	}
	else
	{
		out[0] = 0 - out[0];
	}
	out[2] = 0;
}

// [ta-contact]: on the enemy_visible rising edge, the angle between the
// current view forward and the nearest visible enemy = the in-engine mirror
// of the study's first-sight metric. Telemetry only (k_hm_debug).
static void TA_LogContact(gedict_t *self, ta_bot_t *ta)
{
	gedict_t *best = NULL;
	float best_d = 999999.0f;
	vec3_t eye, fwd, rel;
	float angerr, dot, rlen;
	int i;

	TA_Eye(self, eye);
	for (i = 1; i <= MAX_CLIENTS; i++)
	{
		gedict_t *e = &g_edicts[i];
		float dx, dy, dz, d;

		if ((e == self) || (e->ct != ctPlayer) || ISDEAD(e) || SameTeam(e, self))
		{
			continue;
		}
		traceline(eye[0], eye[1], eye[2], e->s.v.origin[0], e->s.v.origin[1],
					e->s.v.origin[2] + TA_EYE_Z, true, self);
		if (g_globalvars.trace_fraction < 1)
		{
			continue;
		}
		dx = e->s.v.origin[0] - eye[0];
		dy = e->s.v.origin[1] - eye[1];
		dz = e->s.v.origin[2] - eye[2];
		d = dx * dx + dy * dy + dz * dz;
		if (d < best_d)
		{
			best_d = d;
			best = e;
		}
	}

	if (!best)
	{
		return;
	}

	trap_makevectors(self->s.v.v_angle);
	VectorCopy(g_globalvars.v_forward, fwd);
	VectorSubtract(best->s.v.origin, eye, rel);
	rlen = VectorNormalize(rel);
	dot = DotProduct(fwd, rel);
	if (dot > 1.0f)
	{
		dot = 1.0f;
	}
	if (dot < -1.0f)
	{
		dot = -1.0f;
	}
	angerr = acos(dot) * 180.0f / M_PI;

	G_cprint("[ta-contact] bot=%s angerr=%.1f dist=%.0f cell=%s held=%d t=%f\n",
				self->netname, angerr, rlen,
				(ta->cell >= 0) ? ta_cell_dm3[ta->cell].name : "?",
				ta->held, g_globalvars.time);
}

static void TA_Select(gedict_t *self, ta_bot_t *ta)
{
	const ta_cell_t *cell = &ta_cell_dm3[ta->cell];
	vec3_t eye;
	float best_score = 0, best_w = -1;
	int best = -1, best_static = -1;
	qbool rear_hold = false;
	float move_yaw = 0;
	int i;

	TA_Eye(self, eye);

	// rear-check scheduling (tier 3, T6): while relocating, some holds go
	// to the best point >90 degrees off the movement heading
	if (ta_tier >= 3)
	{
		float vx = self->s.v.velocity[0], vy = self->s.v.velocity[1];

		if ((vx * vx + vy * vy) > (100.0f * 100.0f)
				&& (g_globalvars.time >= ta->next_rear) && (ta->next_rear > 0))
		{
			rear_hold = true;
			move_yaw = vectoyaw(self->s.v.velocity);
		}
		if (ta->next_rear <= 0)
		{
			ta->next_rear = g_globalvars.time
					+ ta_rear_period * (0.7f + 0.6f * g_random());
		}
	}

	for (i = cell->first_threat; i < cell->first_threat + cell->n_threats; i++)
	{
		const ta_threat_t *t = &ta_threat_dm3[i];
		vec3_t rel;
		float dist, score;

		VectorSubtract(t->org, eye, rel);
		dist = VectorLength(rel);
		if (dist < TA_MIN_AIM_DIST)
		{
			continue;
		}

		if (t->w > best_w)
		{
			best_w = t->w;
			best_static = i;
		}

		score = t->w;
		if (ta_tier >= 2)
		{
			score *= TA_BSight(self, t) * TA_BItem(self, t) * TA_BTm(self, t);
		}
		if (ta_tier >= 3)
		{
			float since = g_globalvars.time - ta->last_held[i];

			if (ta->last_held[i] > 0)
			{
				score *= 1.0f + ((since > TA_STALE_HORIZON)
						? 1.0f : since / TA_STALE_HORIZON);
			}
			else
			{
				score *= 2.0f; // never held = maximally stale
			}
		}
		// geometry band (T7) + occlusion
		if ((dist < TA_BAND_MIN) || (dist > TA_BAND_MAX))
		{
			score *= 0.7f;
		}
		traceline(eye[0], eye[1], eye[2], t->org[0], t->org[1], t->org[2],
					true, self);
		if (g_globalvars.trace_fraction < 1)
		{
			score = 0;
		}
		if (rear_hold)
		{
			float dyaw = vectoyaw(rel) - move_yaw;

			while (dyaw > 180)
			{
				dyaw -= 360;
			}
			while (dyaw < -180)
			{
				dyaw += 360;
			}
			if (fabs(dyaw) <= 90)
			{
				score = 0;
			}
		}

		if (score > best_score)
		{
			best_score = score;
			best = i;
		}
	}

	if ((best < 0) && rear_hold)
	{
		rear_hold = false;
		// no rear candidate: fall through to the static best below
	}
	if (best < 0)
	{
		best = best_static; // everything occluded: hold the strongest prior
	}
	if (best < 0)
	{
		ta->held = -1;
		return;
	}

	ta->held = best;
	ta->hold_until = g_globalvars.time + ta_hold_min
			+ (ta_hold_max - ta_hold_min) * g_random();
	if (ta_tier >= 3)
	{
		ta->last_held[best] = g_globalvars.time;
		if (rear_hold)
		{
			ta->next_rear = g_globalvars.time
					+ ta_rear_period * (0.7f + 0.6f * g_random());
		}
	}

	if (ta_debug)
	{
		G_cprint("[ta-sel] bot=%s cell=%s point=%s:%d w=%.3f score=%.3f rear=%d t=%f\n",
					self->netname, cell->name,
					ta_cell_dm3[ta_threat_dm3[best].from_cell].name, best,
					ta_threat_dm3[best].w, best_score, rear_hold ? 1 : 0,
					g_globalvars.time);
	}
}

void KBot_ThreatAimFrame(gedict_t *self)
{
	ta_bot_t *ta;
	int e = NUM_FOR_EDICT(self);
	int cell;
	vec3_t ang;

	if (!ta_map_ok || !self->isBot || !self->fb.kbot)
	{
		return;
	}
	if ((e < 1) || (e > MAX_CLIENTS))
	{
		return;
	}

	TA_RefreshCvars();
	if ((ta_tier < 1) || !HMode_Active(self))
	{
		return;
	}

	ta = &ta_bots[e];

	if (!TA_Clear(self))
	{
		if (ta->was_clear && self->fb.enemy_visible && ta_debug)
		{
			TA_LogContact(self, ta);
		}
		ta->was_clear = false;
		ta->held = -1;
		return;
	}

	// cell keying (throttled): nearest study loc point, keep the previous
	// cell through gaps/transit or when the keyed cell has no threat rows
	if (g_globalvars.time >= ta->next_key)
	{
		ta->next_key = g_globalvars.time + 0.1f;
		cell = TA_CellForOrg(self->s.v.origin);
		if ((cell >= 0) && (ta_cell_dm3[cell].n_threats > 0)
				&& (cell != ta->cell))
		{
			ta->cell = cell;
			ta->held = -1; // cell change forces reselect
		}
	}

	if ((ta->cell < 0) || (ta_cell_dm3[ta->cell].n_threats == 0))
	{
		ta->was_clear = true;
		return; // nowhere to aim from here; vanilla look stands
	}

	if ((ta->held < 0) || (g_globalvars.time >= ta->hold_until))
	{
		TA_Select(self, ta);
	}
	if (ta->held < 0)
	{
		ta->was_clear = true;
		return;
	}

	// own the view this frame: recompute angles to the held point (the
	// point is static, the bot moves), clamp the idle pitch envelope --
	// never idle looking up past 5 degrees, cap the down-pitch (T4)
	TA_AnglesTo(self, ta_threat_dm3[ta->held].org, ang);
	if (ang[0] < -5.0f)
	{
		ang[0] = -5.0f;
	}
	if (ang[0] > ta_pitch_cap)
	{
		ang[0] = ta_pitch_cap;
	}
	VectorCopy(ang, self->fb.desired_angle);

	ta->was_clear = true;
}

#endif // BOT_SUPPORT
